/**
 * clinicalPolicyOracleCases.ts
 *
 * Independent Clinical-Policy Ground Truth Oracle for BodyMap AI.
 * Contains 170 clinically grounded exercise-condition scenarios across all 8 categories.
 *
 * Explicitly distinguishes:
 * 1. BLOCK: High-confidence catastrophic contraindication (must be deterministically rejected).
 * 2. ALLOW: Unambiguously safe rehabilitative/functional movement.
 * 3. ALLOW_WITH_GUIDANCE: Context-dependent exercise requiring load/ROM/tempo guidance, NOT deterministic rejection.
 * 4. AMBIGUOUS_ESCALATE: Clinically ambiguous scenario requiring individual clinical assessment/supervision.
 * 5. OUTSIDE_POLICY: Exercise involves body parts unrelated to the declared condition.
 */

export type ClinicalPolicyDecision =
  | 'BLOCK'
  | 'ALLOW'
  | 'ALLOW_WITH_GUIDANCE'
  | 'AMBIGUOUS_ESCALATE'
  | 'OUTSIDE_POLICY'

export interface ClinicalPolicyCase {
  id: number
  categoryKey:
    | 'knee_high_impact'
    | 'shoulder_impingement_cuff'
    | 'lumbar_disc_herniation'
    | 'cervical_spine_pathology'
    | 'cardiac_symptomatic_condition'
    | 'pregnancy_late_stage'
    | 'severe_osteoporosis'
    | 'severe_osteoarthritis'
  categoryLabel: string
  conditionDescription: string
  exerciseName: string
  exerciseFamily: string
  expectedDecision: ClinicalPolicyDecision
  clinicalRationale: string
  isDeterministicFirewallScope: boolean
}

export const CLINICAL_POLICY_CASES: ClinicalPolicyCase[] = [
  // =========================================================================
  // 1. SHOULDER / ROTATOR CUFF / IMPINGEMENT / LABRUM (25 cases)
  // =========================================================================
  {
    id: 1,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Supraspinatus full thickness tear',
    exerciseName: 'Barbell Overhead Press',
    exerciseFamily: 'Overhead Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Full overhead elevation under heavy bilateral load causes severe subacromial compression against the acromion.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 2,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Subacromial impingement syndrome',
    exerciseName: 'Dumbbell Shoulder Press',
    exerciseFamily: 'Overhead Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Overhead dumbbell pressing narrows the subacromial space, pinching inflamed bursa and supraspinatus tendon.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 3,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff tendinopathy',
    exerciseName: 'Behind the Neck Shoulder Press',
    exerciseFamily: 'Behind Neck Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Requires extreme external rotation combined with abduction, placing maximal shear on the anterior capsule and rotator cuff.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 4,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Subacromial bursitis and impingement',
    exerciseName: 'Upright Barbell Rows',
    exerciseFamily: 'Upright Row',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Internal rotation combined with elevation directly impinges the greater tuberosity against the coracoacromial arch.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 5,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'SLAP tear / Superior labral repair',
    exerciseName: 'Parallel Bar Dips',
    exerciseFamily: 'Dips',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'End-range shoulder extension and anterior translation produce severe anterior capsule and superior labral traction.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 6,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff tear',
    exerciseName: 'Weighted Chest Dips',
    exerciseFamily: 'Dips',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Deep dips under additional load severely stress the anterior glenohumeral structures and subacromial space.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 7,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Infraspinatus tendon tear',
    exerciseName: 'Barbell Snatch',
    exerciseFamily: 'Olympic Snatch',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Ballistic overhead catch in deep external rotation exerts extreme shock loads on the rotator cuff and labrum.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 8,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff impingement',
    exerciseName: 'Barbell Clean and Jerk',
    exerciseFamily: 'Olympic Jerk',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'High-velocity explosive overhead lockout risks acute tendon re-tear under dynamic load.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 9,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Shoulder impingement',
    exerciseName: 'Push Press',
    exerciseFamily: 'Overhead Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Dynamic leg drive into overhead lockout creates uncontrolled impact at end-range shoulder elevation.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 10,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff tear',
    exerciseName: 'Handstand Push-ups',
    exerciseFamily: 'Inverted Overhead',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Full bodyweight compressive loading in extreme vertical elevation is catastrophic for damaged cuff tendons.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 11,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Subacromial impingement',
    exerciseName: 'Behind the Neck Lat Pulldown',
    exerciseFamily: 'Behind Neck Pulldown',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Forces extreme horizontal abduction and external rotation, producing acute anterior capsule and subacromial shear.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 12,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Shoulder impingement',
    exerciseName: 'Military Press',
    exerciseFamily: 'Overhead Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Strict bilateral overhead barbell press forces humeral elevation through the primary impingement arc (60-120 deg).',
    isDeterministicFirewallScope: true,
  },
  {
    id: 13,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Subacromial impingement',
    exerciseName: 'Landmine Press',
    exerciseFamily: 'Landmine Angled Press',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Movement occurs at ~45 degrees in the scapular plane, sparing subacromial clearance; acceptable with load guidance.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 14,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff tendinopathy',
    exerciseName: 'Incline Dumbbell Bench Press',
    exerciseFamily: 'Incline Press',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Low-to-moderate incline (<30 deg) avoids vertical overhead position; requires pain-free ROM guidance.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 15,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Shoulder impingement',
    exerciseName: 'Dumbbell Floor Press',
    exerciseFamily: 'Floor Press',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Floor limits shoulder extension to 90 degrees, preventing excessive hyperextension and anterior capsule stress.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 16,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff impingement',
    exerciseName: 'Flat Barbell Bench Press',
    exerciseFamily: 'Bench Press',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Horizontal press without vertical elevation; requires moderate grip and avoidance of extreme bounce.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 17,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Mild subacromial bursitis',
    exerciseName: 'Push-ups',
    exerciseFamily: 'Push-up',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Closed kinetic chain horizontal pressing with free scapular movement is generally well tolerated.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 18,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Anterior labral tear (Bankart)',
    exerciseName: 'Dumbbell Chest Flyes',
    exerciseFamily: 'Chest Flye',
    expectedDecision: 'AMBIGUOUS_ESCALATE',
    clinicalRationale: 'Deep horizontal abduction and external rotation can provoke anterior instability; depends heavily on tear stability.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 19,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Supraspinatus repair',
    exerciseName: 'Cable Face Pulls',
    exerciseFamily: 'Rear Delt / Upper Back',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens posterior rotator cuff and lower trapezius, improving subacromial space clearance.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 20,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff weakness',
    exerciseName: 'Side-Lying External Rotations',
    exerciseFamily: 'Rotator Cuff Rehab',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Targeted strengthening of infraspinatus and teres minor without overhead elevation.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 21,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff impingement',
    exerciseName: 'Lateral Raises below Shoulder Height',
    exerciseFamily: 'Lateral Raise',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Restricting ROM below 75-80 degrees prevents humeral head impingement against the acromial arch.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 22,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Shoulder impingement',
    exerciseName: 'Bicep Hammer Curls',
    exerciseFamily: 'Biceps Isolation',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Forearm flexion with neutral grip places zero subacromial or rotational stress on the shoulder.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 23,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff tear',
    exerciseName: 'Tricep Rope Pushdowns',
    exerciseFamily: 'Triceps Isolation',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Elbow extension with upper arms pinned at sides keeps glenohumeral joint stable in neutral.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 24,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Shoulder impingement',
    exerciseName: 'Seated Leg Press',
    exerciseFamily: 'Lower Body Isolation',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Lower body exercise; no involvement of upper body or glenohumeral structures.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 25,
    categoryKey: 'shoulder_impingement_cuff',
    categoryLabel: 'Shoulder / Rotator Cuff',
    conditionDescription: 'Rotator cuff tendinopathy',
    exerciseName: 'Standing Calf Raises',
    exerciseFamily: 'Calf Isolation',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Lower body movement unrelated to shoulder pathology.',
    isDeterministicFirewallScope: false,
  },

  // =========================================================================
  // 2. LUMBAR SPINE / DISC HERNIATION / SCIATICA (25 cases)
  // =========================================================================
  {
    id: 26,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L4-L5 disc herniation with active radiculopathy',
    exerciseName: 'Heavy Barbell Deadlift',
    exerciseFamily: 'Deadlift',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'High anterior shear and massive compressive intradiscal pressure risk acute nuclear extrusion.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 27,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L5-S1 bulging disc',
    exerciseName: 'Barbell Romanian Deadlift',
    exerciseFamily: 'RDL',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Hip hinge with anterior barbell load creates large lumbar flexion moment arm, stressing posterior disc annulus.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 28,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Barbell Good Mornings',
    exerciseFamily: 'Good Morning',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Extreme resistance moment arm on the lumbar spine under heavy axial load; contraindicated for disc pathology.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 29,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L4-L5 herniated disc',
    exerciseName: 'Weighted Jefferson Curls',
    exerciseFamily: 'Jefferson Curl',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Deliberate end-range loaded lumbar flexion directly strains the posterior annulus fibrosus.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 30,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar spinal stenosis and disc protrusion',
    exerciseName: 'Barbell Back Squat',
    exerciseFamily: 'Back Squat',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Heavy axial bar placement on spine creates high intervertebral disc compression and facet joint loading.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 31,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L5-S1 disc herniation',
    exerciseName: 'Weighted Decline Sit-ups',
    exerciseFamily: 'Loaded Flexion',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Repetitive loaded lumbar flexion generates peak intradiscal pressures exceeding 2000N.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 32,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation with sciatica',
    exerciseName: 'Olympic Power Clean',
    exerciseFamily: 'Olympic Clean',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'High-velocity pull from floor with abrupt catch exerts massive compressive and rotational spinal shock.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 33,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L4-L5 disc herniation',
    exerciseName: 'Stiff-Legged Deadlift',
    exerciseFamily: 'Deadlift',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Straight knee posture maximizes lumbar flexion torque and posterior disc strain.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 34,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Sciatica and disc protrusion',
    exerciseName: 'Sumo Deadlift',
    exerciseFamily: 'Deadlift',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Despite wider stance, heavy floor pull creates high intradiscal compressive forces contraindicated for acute disc injuries.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 35,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Barbell Clean and Press',
    exerciseFamily: 'Olympic Clean & Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Combines dynamic floor pull with overhead extension, compounding axial and shear loads on damaged discs.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 36,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Weighted Spinal Hyperextensions',
    exerciseFamily: 'Loaded Extension',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Loaded hyperextension impinges posterior facet joints and compresses posterior disc margin.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 37,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L5-S1 disc bulge',
    exerciseName: 'Goblet Squat with light dumbbell',
    exerciseFamily: 'Front-Loaded Squat',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Anterior load encourages upright torso with reduced lumbar shear; requires load and depth limitation.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 38,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Bodyweight Single-Leg Deadlift',
    exerciseFamily: 'Unweighted Hinge',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Minimal spinal compression; requires hamstring flexibility and pelvis stability guidance.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 39,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L4-L5 disc herniation',
    exerciseName: 'Bird-Dog',
    exerciseFamily: 'Spine-Neutral Core',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'McGill Big 3 core exercise: builds extensor endurance with minimal compressive disc load.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 40,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Dead Bug',
    exerciseFamily: 'Spine-Neutral Core',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Maintains flat neutral lumbar spine while moving extremities; gold standard for disc rehabilitation.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 41,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation with sciatica',
    exerciseName: 'Side Plank',
    exerciseFamily: 'Spine-Neutral Core',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'High quadratus lumborum recruitment with low spinal axial compression.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 42,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L5-S1 disc bulge',
    exerciseName: 'Pallof Press',
    exerciseFamily: 'Anti-Rotation Core',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Trains rotational stability and core bracing without spinal twisting or flexion.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 43,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Glute Bridge',
    exerciseFamily: 'Hip Extension',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Activates glutes and hamstrings with neutral spine and zero axial load.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 44,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Bodyweight Air Squats',
    exerciseFamily: 'Bodyweight Squat',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Unloaded parallel squat maintains neutral spine without external axial compression.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 45,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Stationary Recumbent Bike',
    exerciseFamily: 'Low-Impact Cardio',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Supported backrest maintains neutral spine during gentle cardiovascular conditioning.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 46,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Severe L4-L5 disc herniation',
    exerciseName: 'Seated Cable Row',
    exerciseFamily: 'Horizontal Row',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Safe if torso is held strictly upright and neutral; hazardous if allowed to round forward into flexion.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 47,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Standing Dumbbell Bicep Curls',
    exerciseFamily: 'Arm Isolation',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Upper body isolation exercise with negligible lumbar stress when performed without swinging.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 48,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Flat Dumbbell Bench Press',
    exerciseFamily: 'Chest Press',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Back supported by bench; requires avoidance of excessive lumbar arching.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 49,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'L4-L5 disc herniation',
    exerciseName: 'Seated Leg Extension Machine',
    exerciseFamily: 'Quad Isolation',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Back supported against back pad; minimal lumbar spine loading.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 50,
    categoryKey: 'lumbar_disc_herniation',
    categoryLabel: 'Lumbar Spine / Disc',
    conditionDescription: 'Lumbar disc herniation',
    exerciseName: 'Seated Torso Rotation Machine',
    exerciseFamily: 'Loaded Rotation',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Loaded spinal twisting produces severe circumferential shear on disc annulus fibres.',
    isDeterministicFirewallScope: true,
  },

  // =========================================================================
  // 3. KNEE / ACL / MENISCUS (25 cases)
  // =========================================================================
  {
    id: 51,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Acute ACL tear',
    exerciseName: 'Explosive Box Jumps',
    exerciseFamily: 'Plyometric Jump',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Landing ground reaction forces produce intense anterior tibial translation and knee shear, risking catastrophic joint collapse.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 52,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Meniscus tear',
    exerciseName: 'Depth Jumps from 24 inch box',
    exerciseFamily: 'Plyometric Drop',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Massive shock impact on ground landing crushes torn meniscus between femoral condyle and tibial plateau.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 53,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL tear',
    exerciseName: 'Jump Squats',
    exerciseFamily: 'Plyometric Jump',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Ballistic takeoff and landing create extreme shear forces contraindicated for unstable knee ligaments.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 54,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Meniscal tear',
    exerciseName: 'Burpees with jump',
    exerciseFamily: 'High-Impact Calisthenics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Rapid transition into deep knee flexion followed by explosive jumping strains meniscal horns.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 55,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Patellar dislocation and instability',
    exerciseName: 'Jumping Split Lunges',
    exerciseFamily: 'Plyometric Lunge',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Dynamic landing with single-leg deceleration creates high patellofemoral shear and lateral dislocation forces.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 56,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'MCL sprain grade 2',
    exerciseName: 'Lateral Skater Bounds',
    exerciseFamily: 'Lateral Plyometrics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Lateral cutting and single-leg landing apply acute valgus stress directly across the medial collateral ligament.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 57,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL reconstruction',
    exerciseName: 'Double Unders Jump Rope',
    exerciseFamily: 'Impact Skipping',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Repetitive high-frequency ballistic impact without stabilization threatens graft integration.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 58,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Meniscus tear',
    exerciseName: 'Tuck Jumps',
    exerciseFamily: 'Plyometric Jump',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Maximum vertical jump with deep knee flexion landing creates severe tibiofemoral impact.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 59,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL tear',
    exerciseName: 'Broad Jumps',
    exerciseFamily: 'Plyometric Jump',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Horizontal deceleration on landing generates high anterior tibial shear forces that directly load the ACL.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 60,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Patellar tendinopathy',
    exerciseName: 'Power Skips',
    exerciseFamily: 'Plyometrics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Ballistic single-leg propulsion exerts sharp tensile shock directly through the patellar tendon.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 61,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL tear / reconstruction',
    exerciseName: 'Seated Leg Extension Machine (0-45 deg)',
    exerciseFamily: 'Open-Chain Knee Extension',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'OKC quad extensions produce maximal anterior tibial shear; NOT a universally safe exemption. Requires ROM/phase guidance.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 62,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL tear',
    exerciseName: 'Seated Hamstring Curls',
    exerciseFamily: 'Hamstring Isolation',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Hamstrings act as primary ACL agonists, pulling tibia posteriorly to protect the cruciate ligament.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 63,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Meniscus tear',
    exerciseName: 'Straight-Leg Raises',
    exerciseFamily: 'Closed/Isometric Quad',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens quadriceps without knee joint movement, eliminating intra-articular shear.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 64,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL tear',
    exerciseName: 'Wall Sits (parallel)',
    exerciseFamily: 'Isometric Quad',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Isometric co-contraction provides joint stability without dynamic deceleration forces.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 65,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Knee injury',
    exerciseName: 'Glute Bridges',
    exerciseFamily: 'Posterior Chain',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Posterior chain recruitment with minimal knee flexion torque.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 66,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL rehabilitation',
    exerciseName: 'Stationary Cycling (low resistance)',
    exerciseFamily: 'Low-Impact Cardio',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Smooth non-impact circular motion promotes synovial fluid circulation and ROM recovery.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 67,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Meniscus tear',
    exerciseName: 'Swimming (gentle freestyle)',
    exerciseFamily: 'Aquatic Cardio',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Buoyancy eliminates gravitational joint impact while maintaining cardiovascular conditioning.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 68,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL tear',
    exerciseName: 'Box Squats (sitting to 16 inch box)',
    exerciseFamily: 'Supported Squat',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Controlled sitting back onto box reduces anterior knee translation; requires slow descent and no bouncing.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 69,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Meniscus injury',
    exerciseName: 'Low Bench Step-ups (6 inch height)',
    exerciseFamily: 'Step-up',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Low step height keeps knee flexion within safe limits; requires stepping down gently without jumping.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 70,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Knee ACL tear',
    exerciseName: 'Bodyweight Squats to Parallel',
    exerciseFamily: 'Bodyweight Squat',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Unloaded movement allows patient to self-regulate depth and maintain pain-free limits.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 71,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Meniscus tear',
    exerciseName: 'Deep Pistol Squats (Single Leg to floor)',
    exerciseFamily: 'Extreme Deep Squat',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Extreme single-leg knee flexion (>120 deg) generates peak posterior horn meniscal compression and shear.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 72,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Knee injury',
    exerciseName: 'Seated Overhead Dumbbell Press',
    exerciseFamily: 'Shoulder Press',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Upper body exercise performed seated; zero knee involvement.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 73,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'ACL tear',
    exerciseName: 'Lat Pulldowns',
    exerciseFamily: 'Back Pulldown',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Upper body movement with thighs secured under pads; no knee impact.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 74,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Knee cartilage damage',
    exerciseName: 'Bench Press',
    exerciseFamily: 'Chest Press',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Upper body press with feet planted passively; zero knee stress.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 75,
    categoryKey: 'knee_high_impact',
    categoryLabel: 'Knee / ACL / Meniscus',
    conditionDescription: 'Patellofemoral pain syndrome',
    exerciseName: 'Clamshells with resistance band',
    exerciseFamily: 'Hip Abduction',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens gluteus medius to correct dynamic knee valgus without knee joint loading.',
    isDeterministicFirewallScope: true,
  },

  // =========================================================================
  // 4. CERVICAL SPINE / NECK PATHOLOGY (20 cases)
  // =========================================================================
  {
    id: 76,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'C5-C6 cervical disc herniation',
    exerciseName: 'Behind the Neck Barbell Shoulder Press',
    exerciseFamily: 'Behind Neck Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Requires cervical flexion while barbell rests/moves directly adjacent to C5-C7 spinous processes under load.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 77,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical spinal fusion C4-C6',
    exerciseName: 'Wrestler Bridge',
    exerciseFamily: 'Neck Bridge',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Places full bodyweight axial compression directly onto cervical vertebrae in extreme hyperextension; catastrophic risk.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 78,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical radiculopathy',
    exerciseName: 'Headstand against wall',
    exerciseFamily: 'Inverted Posture',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Direct axial bodyweight compression on the cervical spine closes intervertebral foramina and compresses nerve roots.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 79,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical disc herniation',
    exerciseName: 'Handstand Push-ups',
    exerciseFamily: 'Inverted Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Uncontrolled descent can drive the head into the floor, transmitting severe compressive force through the cervical spine.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 80,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical spine pathology',
    exerciseName: 'Shoulder Stand (Sarvangasana)',
    exerciseFamily: 'Inverted Yoga',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Forces extreme cervical hyperflexion supporting lower body mass on the neck and upper thoracic spine.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 81,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'C5-C6 disc herniation',
    exerciseName: 'Behind the Neck Lat Pulldown',
    exerciseFamily: 'Behind Neck Pulldown',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Forward head posture under cable tension pinches cervical nerve roots and increases shear.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 82,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical fusion',
    exerciseName: 'Olympic Split Jerk',
    exerciseFamily: 'Olympic Jerk',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Heavy barbell dynamically locked out above head risks accidental impact or transmission of heavy shock through the neck.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 83,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical disc herniation',
    exerciseName: 'Barbell High-Bar Back Squat with heavy bar on neck',
    exerciseFamily: 'Back Squat (Neck Resting)',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Bar resting directly across C7-T1 creates severe direct mechanical compression on the herniated cervical region.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 84,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical spine pathology',
    exerciseName: 'Weighted Neck Harness Extension',
    exerciseFamily: 'Weighted Neck Harness',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Directly loads cervical spine into extension with hanging weights; extreme risk of disc herniation exacerbation.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 85,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical radiculopathy',
    exerciseName: 'Chin Tucks (Cervical Retraction)',
    exerciseFamily: 'Cervical Stabilization',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'McKenzie cervical retraction opens intervertebral foramina and reduces nerve root compression.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 86,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical spine pathology',
    exerciseName: 'Isometric Neck Strengthening (neutral)',
    exerciseFamily: 'Isometric Neck',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens deep cervical flexors and extensors without joint movement or compressive loading.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 87,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical disc herniation',
    exerciseName: 'Seated Chest Press Machine',
    exerciseFamily: 'Machine Chest Press',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Head supported against back pad keeps cervical spine neutral and unloaded.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 88,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical spine pathology',
    exerciseName: 'Stationary Upright Bike',
    exerciseFamily: 'Cardio',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Upright posture prevents neck hyperextension; smooth low-impact cardio.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 89,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical radiculopathy',
    exerciseName: 'Walking on Flat Treadmill',
    exerciseFamily: 'Walking',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Gentle low-impact ambulation keeps spine upright and mobile.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 90,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical disc herniation',
    exerciseName: 'Lying Hamstring Curls',
    exerciseFamily: 'Leg Curl',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Lower body machine exercise; no load transmitted to cervical spine.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 91,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical fusion',
    exerciseName: 'Standing Calf Raises',
    exerciseFamily: 'Calf Raise',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Safe with dumbbells held at sides; avoid standing calf raise machine with shoulder pads that transmit axial load through spine.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 92,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical spine pathology',
    exerciseName: 'Glute Bridges',
    exerciseFamily: 'Hip Extension',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Safe if weight is supported on upper back/scapulae; must avoid driving weight directly onto the back of the neck.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 93,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical disc herniation',
    exerciseName: 'Dead Bug',
    exerciseFamily: 'Core',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Supine core stabilization with head resting peacefully on mat.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 94,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical radiculopathy',
    exerciseName: 'Bird-Dog',
    exerciseFamily: 'Core',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Quadruped posture with neutral neck gazing at floor; strengthens posterior chain without neck strain.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 95,
    categoryKey: 'cervical_spine_pathology',
    categoryLabel: 'Cervical Spine / Neck',
    conditionDescription: 'Cervical spine pathology',
    exerciseName: 'Scapular Wall Slides',
    exerciseFamily: 'Scapular Mobility',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Promotes thoracic and scapular movement, reducing compensatory cervical strain.',
    isDeterministicFirewallScope: true,
  },

  // =========================================================================
  // 5. CARDIAC / SYMPTOMATIC CARDIOVASCULAR (25 cases)
  // =========================================================================
  {
    id: 96,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Coronary artery disease and angina',
    exerciseName: 'High-Intensity Interval Training (HIIT Cardio)',
    exerciseFamily: 'HIIT',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Rapidly spikes myocardial oxygen consumption (MVO2) past the ischemic threshold, triggering acute angina or infarction.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 97,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Recent myocardial infarction',
    exerciseName: 'All-Out 100m Sprint Intervals',
    exerciseFamily: 'Sprint',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Massive catecholamine surge and anaerobic demand risk lethal ventricular arrhythmias.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 98,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Congestive heart failure',
    exerciseName: 'Tabata Sprints on AirBike to exhaustion',
    exerciseFamily: 'Tabata',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Supramaximal effort overwhelms failing left ventricular stroke volume, causing acute pulmonary edema.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 99,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Severe aortic stenosis',
    exerciseName: '1RM Strength Testing Attempt',
    exerciseFamily: '1RM Test',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Extreme afterload and sudden blood pressure elevation across a fixed stenotic valve causes syncope or sudden cardiac death.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 100,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Severe uncontrolled hypertension',
    exerciseName: 'Heavy Leg Press with Maximal Valsalva',
    exerciseFamily: 'Heavy Valsalva Lift',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Valsalva maneuver combined with heavy lower body pressing spikes systolic BP > 300 mmHg, risking stroke or aortic dissection.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 101,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Hypertrophic cardiomyopathy',
    exerciseName: 'Sprint Interval Training',
    exerciseFamily: 'Sprint Intervals',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Dynamic outflow tract obstruction increases dramatically under high inotropic/chronotropic sprint demand.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 102,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Coronary artery disease',
    exerciseName: 'Heavy Barbell Deadlift 1RM',
    exerciseFamily: 'Maximal Heavy Lift',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Maximal 1RM attempts elicit mandatory breath-holding and intense hemodynamic strain.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 103,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Angina pectoris',
    exerciseName: 'High-Impact Burpee Intervals',
    exerciseFamily: 'High-Impact Calisthenics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Combines rapid postural changes with high anaerobic cardiovascular demand.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 104,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Cardiac stent placed 6 months ago',
    exerciseName: 'Outdoor Hill Sprints to failure',
    exerciseFamily: 'Sprints',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Maximal exertion to failure induces dangerous coronary shear and ischemia.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 105,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Coronary artery disease',
    exerciseName: 'Zone 2 Walking on Flat Surface',
    exerciseFamily: 'Walking',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Low-intensity steady aerobic activity improves endothelial function and cardiovascular health without ischemic risk.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 106,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Stable coronary artery disease',
    exerciseName: 'Stationary Cycling (low resistance, light pace)',
    exerciseFamily: 'Stationary Bike',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Permits steady, controlled heart rate elevation below the ischemic threshold.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 107,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Controlled hypertension',
    exerciseName: 'Gentle Swimming / Water Aerobics',
    exerciseFamily: 'Aquatics',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Water immersion promotes venous return; comfortable pace prevents pressure spikes.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 108,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Stable angina',
    exerciseName: 'Light Resistance Band Rows with continuous breathing',
    exerciseFamily: 'Band Resistance',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Safe if RPE remains < 13/20 and patient avoids breath-holding (Valsalva).',
    isDeterministicFirewallScope: false,
  },
  {
    id: 109,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Severe symptomatic aortic stenosis',
    exerciseName: 'Outdoor Jogging',
    exerciseFamily: 'Jogging',
    expectedDecision: 'AMBIGUOUS_ESCALATE',
    clinicalRationale: 'In severe aortic stenosis, even light jogging can exceed fixed cardiac output; requires formal cardiology clearance.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 110,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Coronary artery disease',
    exerciseName: 'Gentle Mobility and Stretching',
    exerciseFamily: 'Mobility',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Parasympathetic stimulation, minimal cardiovascular demand.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 111,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Hypertension',
    exerciseName: 'Bodyweight Glute Bridges',
    exerciseFamily: 'Bodyweight Resistance',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Mild functional strength without intense cardiovascular or pressor response.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 112,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Cardiac pathology',
    exerciseName: 'Light Dumbbell Bicep Curls (15 reps, easy weight)',
    exerciseFamily: 'Arm Isolation',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Low-weight high-rep arm exercises are standard in Phase 2 cardiac rehab; must breathe continuously.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 113,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Cardiac stent',
    exerciseName: 'Steady State Elliptical (low level)',
    exerciseFamily: 'Elliptical',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Smooth non-impact cardio with easily controllable intensity.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 114,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Coronary artery disease',
    exerciseName: 'Bird-Dog',
    exerciseFamily: 'Core',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Low-stress stabilization without Valsalva.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 115,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Heart failure NYHA Class II',
    exerciseName: 'Walking 20 minutes at conversation pace',
    exerciseFamily: 'Walking',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Aerobic walking improves ejection fraction and quality of life in compensated HF.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 116,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Coronary artery disease',
    exerciseName: 'Max Rep Push-ups to failure',
    exerciseFamily: 'Push-up to Failure',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Pushing to failure elicits involuntary Valsalva and high pressor response contraindicated in CAD.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 117,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Cardiac condition',
    exerciseName: 'Seated Calf Raises',
    exerciseFamily: 'Calf Isolation',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Minimal cardiovascular stress; promotes lower limb venous return (calf muscle pump).',
    isDeterministicFirewallScope: true,
  },
  {
    id: 118,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Cardiac condition',
    exerciseName: 'Foam Rolling Quad and IT Band',
    exerciseFamily: 'Self-Myofascial Release',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Passive soft tissue recovery without cardiovascular load.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 119,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Coronary artery disease',
    exerciseName: 'Seated Deep Breathing / Meditation',
    exerciseFamily: 'Breathwork',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Reduces sympathetic tone, lowering blood pressure and heart rate.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 120,
    categoryKey: 'cardiac_symptomatic_condition',
    categoryLabel: 'Cardiac Pathology',
    conditionDescription: 'Coronary artery disease',
    exerciseName: 'Knee sleeve application',
    exerciseFamily: 'Gear',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Passive equipment; unrelated to cardiac physiology.',
    isDeterministicFirewallScope: false,
  },

  // =========================================================================
  // 6. PREGNANCY (TRIMESTER-AWARE) (20 cases)
  // =========================================================================
  {
    id: 121,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy (32 weeks)',
    exerciseName: 'Prone Superman Extensions (lying on belly)',
    exerciseFamily: 'Prone Hyperextension',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Prone lying compresses the gravid uterus and placenta directly against the floor.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 122,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Late pregnancy 28 weeks gestation',
    exerciseName: 'Flat Barbell Bench Press (prolonged supine)',
    exerciseFamily: 'Flat Supine Press',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Gravid uterus compresses inferior vena cava and descending aorta, causing maternal hypotension and decreased uteroplacental perfusion.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 123,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: '34 weeks pregnant',
    exerciseName: 'Explosive Box Jumps',
    exerciseFamily: 'Plyometrics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'High fall risk and ballistic pelvic floor impact; relaxin-induced ligamentous laxity increases joint injury risk.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 124,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Full Burpees with chest to floor',
    exerciseFamily: 'Burpee',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Direct abdominal impact against floor combined with ballistic jumping.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 125,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Second trimester (22 weeks pregnant)',
    exerciseName: 'Lying Flat on Stomach Cobra',
    exerciseFamily: 'Prone',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Direct mechanical compression of the enlarged gravid uterus.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 126,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Weighted Decline Crunches',
    exerciseFamily: 'Abdominal Flexion',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Exacerbates diastasis recti, increases intra-abdominal pressure, and strains weakened linea alba.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 127,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'First trimester (8 weeks pregnant)',
    exerciseName: 'Flat Dumbbell Bench Press',
    exerciseFamily: 'Flat Bench',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'In 1st trimester (<14 weeks), the uterus is within the pelvic cavity and does not compress the vena cava; flat bench is not contraindicated.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 128,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester (30 weeks)',
    exerciseName: 'Incline Dumbbell Bench Press (30-45 deg incline)',
    exerciseFamily: 'Incline Press',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Incline angle prevents uterine compression on the inferior vena cava while allowing upper body pressing.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 129,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Cat-Cow Mobility',
    exerciseFamily: 'Pelvic Mobility',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Quadruped position relieves spinal pressure and improves pelvic mobility.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 130,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Late pregnancy',
    exerciseName: 'Side-Lying Leg Lifts',
    exerciseFamily: 'Side-Lying Hip',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Left side-lying position optimizes vena cava blood flow while strengthening hip abductors.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 131,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Pelvic Tilts against wall',
    exerciseFamily: 'Pelvic Floor',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Relieves lower back ache and strengthens pelvic stabilizers safely.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 132,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Second trimester (20 weeks)',
    exerciseName: 'Prenatal Gentle Yoga',
    exerciseFamily: 'Prenatal Yoga',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Tailored for pregnancy with no inversions, no prone postures, and supported transitions.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 133,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Walking 30 minutes at moderate pace',
    exerciseFamily: 'Walking',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'ACOG recommended low-impact cardiovascular exercise throughout pregnancy.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 134,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Second trimester pregnancy',
    exerciseName: 'Stationary Cycling (upright handlebars)',
    exerciseFamily: 'Cycling',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Zero impact, no road hazard or fall risk compared to outdoor bicycling.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 135,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Deep Scuba Diving',
    exerciseFamily: 'Diving',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Fetal pulmonary circulation cannot filter nitrogen bubbles; absolute contraindication throughout all pregnancy.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 136,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Seated Bicep Curls',
    exerciseFamily: 'Arm Isolation',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Upper body isolation seated with back support; no abdominal or uterine pressure.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 137,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Postpartum 8 weeks ago',
    exerciseName: 'Flat Bench Press',
    exerciseFamily: 'Flat Bench',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Postpartum client is no longer carrying a fetus; inferior vena cava compression does not occur.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 138,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Deep Sissy Squats with backward lean',
    exerciseFamily: 'Extreme Squats',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Severe fall hazard, extreme knee shear, and intense pelvic floor strain.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 139,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Second trimester pregnancy',
    exerciseName: 'Standing Band Pull-Aparts',
    exerciseFamily: 'Upper Back',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens upper back to counter forward kyphosis of pregnancy without spinal or abdominal strain.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 140,
    categoryKey: 'pregnancy_late_stage',
    categoryLabel: 'Pregnancy Late Stage',
    conditionDescription: 'Third trimester pregnancy',
    exerciseName: 'Kegel Pelvic Floor Contractions',
    exerciseFamily: 'Pelvic Floor',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'ACOG gold standard for maintaining pelvic floor integrity.',
    isDeterministicFirewallScope: true,
  },

  // =========================================================================
  // 7. SEVERE OSTEOPOROSIS / BONE FRAGILITY (15 cases)
  // =========================================================================
  {
    id: 141,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Severe osteoporosis with T-score -3.5',
    exerciseName: 'Barbell Jefferson Curls',
    exerciseFamily: 'Loaded Spinal Flexion',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'End-range loaded spinal flexion concentrates massive compressive force on fragile anterior vertebral bodies, causing wedge fractures.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 142,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Osteoporosis with prior vertebral compression fracture',
    exerciseName: 'Weighted Russian Twists',
    exerciseFamily: 'Loaded Rotation',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Combines spinal flexion with ballistic rotation, creating severe torsional and compressive shear across osteoporotic vertebrae.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 143,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Severe osteoporosis',
    exerciseName: 'Weighted Crunches / Sit-ups',
    exerciseFamily: 'Spinal Flexion',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Repetitive dynamic spinal flexion is explicitly contraindicated by National Osteoporosis Foundation guidelines.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 144,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Severe osteoporosis',
    exerciseName: 'Plyometric Box Jumps from 30 inches',
    exerciseFamily: 'High-Impact Jumping',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Ballistic landing forces risk femoral neck and vertebral fragility fractures.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 145,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Osteoporosis high fracture risk',
    exerciseName: 'Burpees with jump landing',
    exerciseFamily: 'High-Impact Plyometrics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'High fall and landing fracture risk on vulnerable wrists, hips, and spine.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 146,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Severe osteoporosis',
    exerciseName: 'Heavy Barbell Deadlift 1RM',
    exerciseFamily: 'Maximal Heavy Lift',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Maximal deadlifting creates compressive loads exceeding fracture thresholds of osteoporotic vertebral bone.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 147,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Severe osteoporosis',
    exerciseName: 'Weight-Bearing Brisk Walking',
    exerciseFamily: 'Weight-Bearing Walking',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Stimulates bone mineral density via gentle piezoelectric osteoblast activation without fracture risk.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 148,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Osteoporosis',
    exerciseName: 'Resistance Band Seated Rows',
    exerciseFamily: 'Resistance Band',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens thoracic extensors and posture without spinal compressive impact.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 149,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Osteoporosis',
    exerciseName: 'Single-Leg Balance Exercises near wall',
    exerciseFamily: 'Balance & Fall Prevention',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Critical fall-prevention training; supported balance drills reduce fracture risk.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 150,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Osteoporosis',
    exerciseName: 'Tai Chi for Balance',
    exerciseFamily: 'Mind-Body Balance',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Evidence-based intervention proven to reduce falls and hip fractures in elderly osteoporotic populations.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 151,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Severe osteoporosis',
    exerciseName: 'Wall Push-ups',
    exerciseFamily: 'Wall Upper Body',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Gentle upper-body bone loading without heavy wrist extension impact.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 152,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Osteoporosis',
    exerciseName: 'Bird-Dog',
    exerciseFamily: 'Core',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens back extensors with zero spinal flexion; safe for bone density recovery.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 153,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Osteoporosis with prior wrist fracture',
    exerciseName: 'Seated Leg Press with light weight',
    exerciseFamily: 'Machine Leg Press',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Safe bone loading for femur/pelvis if lower back is firmly kept against seat and load is moderate.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 154,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Severe osteoporosis',
    exerciseName: 'High-Impact Trampoline Jumping',
    exerciseFamily: 'Rebounder',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Uncontrolled deceleration and fall risk make rebounding unsafe for fragile bone.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 155,
    categoryKey: 'severe_osteoporosis',
    categoryLabel: 'Severe Osteoporosis',
    conditionDescription: 'Severe osteoporosis',
    exerciseName: 'Glute Bridges with flat spine',
    exerciseFamily: 'Hip Extension',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Safe hip extensor strengthening without spinal flexion.',
    isDeterministicFirewallScope: true,
  },

  // =========================================================================
  // 8. SEVERE OSTEOARTHRITIS / JOINT DEGENERATION (15 cases)
  // =========================================================================
  {
    id: 156,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe bone on bone knee osteoarthritis',
    exerciseName: 'Maximal Height Box Jumps',
    exerciseFamily: 'Plyometrics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Ballistic impact generates 4-6x bodyweight peak joint reaction forces, grinding exposed subchondral bone.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 157,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe knee osteoarthritis',
    exerciseName: 'Depth Jumps from 18 inches',
    exerciseFamily: 'Plyometrics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'High drop landing impact accelerates joint space narrowing and bone spur microfractures.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 158,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe bilateral knee osteoarthritis',
    exerciseName: 'Jumping Lunges',
    exerciseFamily: 'Plyometric Lunges',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Single-leg ballistic deceleration produces acute patellofemoral and tibiofemoral cartilage shear.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 159,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe osteoarthritis',
    exerciseName: 'Jump Squats with impact landing',
    exerciseFamily: 'Plyometric Squat',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Repeated high-impact landings cause acute joint effusion and severe pain flares.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 160,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe hip and knee osteoarthritis',
    exerciseName: 'Burpees with jump',
    exerciseFamily: 'High-Impact Calisthenics',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Ballistic landing shock severely stresses worn hip and knee articular cartilage.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 161,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe knee osteoarthritis',
    exerciseName: 'Heated Pool Water Aerobics',
    exerciseFamily: 'Aquatic Therapy',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Hydrostatic buoyancy unloads joint surfaces up to 90%, enabling pain-free active ROM.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 162,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe osteoarthritis',
    exerciseName: 'Lap Swimming (gentle freestyle)',
    exerciseFamily: 'Swimming',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Non-weight-bearing cardiovascular exercise promotes cartilage synovial nutrition.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 163,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe knee osteoarthritis',
    exerciseName: 'Recumbent Stationary Bike',
    exerciseFamily: 'Recumbent Bike',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Smooth non-impact circular pedaling with back support; minimizes peak knee compression.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 164,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe osteoarthritis',
    exerciseName: 'Low-Impact Elliptical Gliding',
    exerciseFamily: 'Elliptical',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Feet remain in continuous contact with pedals, eliminating heel-strike shock forces.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 165,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe knee osteoarthritis',
    exerciseName: 'Straight-Leg Raises (supine)',
    exerciseFamily: 'Isometric Quad',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens quadriceps without joint movement or cartilage grinding.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 166,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe knee osteoarthritis',
    exerciseName: 'Isometric Wall Sit (shallow 30 deg bend)',
    exerciseFamily: 'Isometric Squat',
    expectedDecision: 'ALLOW_WITH_GUIDANCE',
    clinicalRationale: 'Safe if kept to shallow knee flexion (<30 deg); deep wall sits increase patellofemoral compressive force.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 167,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe osteoarthritis',
    exerciseName: 'Seated Ankle Circles & Knee Mobility',
    exerciseFamily: 'Seated Mobility',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Gentle active range of motion stimulates synovial fluid production.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 168,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe knee osteoarthritis',
    exerciseName: 'High-Impact Sprints on Asphalt',
    exerciseFamily: 'Impact Running',
    expectedDecision: 'BLOCK',
    clinicalRationale: 'Ground reaction forces on hard pavement transmit destructive shock directly into bone-on-bone joints.',
    isDeterministicFirewallScope: true,
  },
  {
    id: 169,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe knee osteoarthritis',
    exerciseName: 'Seated Upper Body Dumbbell Curls',
    exerciseFamily: 'Arm Isolation',
    expectedDecision: 'OUTSIDE_POLICY',
    clinicalRationale: 'Upper body seated exercise; zero joint loading on lower extremity arthritic joints.',
    isDeterministicFirewallScope: false,
  },
  {
    id: 170,
    categoryKey: 'severe_osteoarthritis',
    categoryLabel: 'Severe Osteoarthritis',
    conditionDescription: 'Severe knee osteoarthritis',
    exerciseName: 'Glute Bridges (unloaded)',
    exerciseFamily: 'Hip Extension',
    expectedDecision: 'ALLOW',
    clinicalRationale: 'Strengthens posterior chain without high knee joint reaction forces.',
    isDeterministicFirewallScope: true,
  },
]
