import type { FormData } from '../types/formData'

export function generatePlanPrompt(formData: FormData): string {

  return [
    'You are an elite exercise physiologist and sports nutritionist with 20+ years coaching experience.',
    '',
    'Generate a complete, hyper-personalized 7-day home workout and meal schedule based on these exact client metrics:',
    '',
    'Client Metrics:',
    `- Age: ${formData.age || '25'} years`,
    `- Gender: ${formData.gender || 'Not specified'}`,
    `- Height: ${formData.height || '175'} cm`,
    `- Weight: ${formData.weight || '70'} kg`,
    `- Fitness Level: ${formData.fitnessLevel || 'Intermediate'}`,
    `- Push-ups baseline capacity: ${formData.pushupCount || 'Not specified'}`,
    '',
    'Goals & Constraints:',
    `- Primary Goal: ${formData.mainGoal || 'Build Lean Muscle'}`,
    `- Targeted Muscle Focus Areas: ${formData.bodyFocus.join(', ') || 'Full Body'}`,
    `- Daily Workout Duration: ${formData.timePerDay || '45'} minutes/day`,
    `- Planned Rest / Recovery Days: ${formData.recoveryDays || '2'} days/week`,
    '',
    'Health & Gear:',
    `- Medical / Injuries / Limitations: ${formData.medicalIssues || 'None stated'}`,
    `- Available Equipment: ${formData.equipment.join(', ') || 'Bodyweight only'}`,
    '',
    'Nutrition & Recovery:',
    `- Dietary Preference: ${formData.dietaryPreference || 'Omnivore'}`,
    `- Allergies / Intolerances: ${formData.allergies || 'None'}`,
    `- Special Meal Requests: ${formData.specialRequests || 'None'}`,
    `- Nightly Sleep: ${formData.sleepHours || '7-8'} hours/night`,
    `- Stress Level: ${formData.stressLevel || 'Moderate'}`,
    '',
    'Formatting Guidelines:',
    '1. Divide clearly into 7 distinct days (Day 1 through Day 7).',
    `2. Allocate ${formData.recoveryDays || '2'} rest/active recovery days across the week.`,
    '3. For each workout day provide: 5-minute dynamic warm-up, main exercise circuit with exact sets/reps/rest, and 5-minute cool-down.',
    '4. For each day provide: Breakfast, Lunch, Dinner, and 1-2 Snacks with realistic ingredient suggestions and approximate calorie targets.',
    '5. Conclude with an inspiring motivational coaching quote.',
    '',
    'CRITICAL SAFETY DIRECTIVES:',
    '1. MEDICAL & INJURY CONTRAINDICATIONS: If the client lists ANY medical condition, injury, pain, surgery, or physical limitation, strictly accommodate it. NEVER prescribe exercises that aggravate declared conditions (e.g., NO jumping, plyometrics, or deep heavy squats for knee/ACL/meniscus injuries; NO overhead pressing for shoulder/rotator cuff injuries; NO heavy spinal loading, deadlifts, or unsupported forward flexion for lumbar disc herniations; NO high-intensity cardio, valsalva straining, or isometric strain for chest pain, heart conditions, or severe hypertension; NO prone or high-impact exercises for pregnancy; NO high-impact bounding for severe osteoarthritis or osteoporosis). Provide safe, low-impact rehabilitative alternatives.',
    '2. ALLERGY EXCLUSIONS: Strictly omit all declared food allergens, intolerances, and related derivatives.'
  ].join('\n')
}


export class AllergenSafetyError extends Error {
  status: number
  allergenCategories?: string[]

  constructor(message: string, allergenCategories?: string[]) {
    super(message)
    this.name = 'AllergenSafetyError'
    this.status = 422
    this.allergenCategories = allergenCategories
  }
}

export async function callGeminiWithFormData(formData: FormData): Promise<string> {
  const response = await fetch('/api/generate-plan', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ formData }),
    signal: AbortSignal.timeout(30000),
  })

  if (!response.ok) {
    const errBody = await response.text()
    if (response.status === 422) {
      try {
        const parsed = JSON.parse(errBody)
        throw new AllergenSafetyError(
          parsed.error || 'ALLERGEN_SAFETY_VIOLATION: Generated plan could not be made safe for declared allergies.',
          parsed.allergenCategories
        )
      } catch (e) {
        if (e instanceof AllergenSafetyError) throw e
        throw new AllergenSafetyError('ALLERGEN_SAFETY_VIOLATION')
      }
    }
    throw new Error(`API error (${response.status}): ${errBody}`)
  }

  const data = await response.json() as { plan?: string; error?: string }
  if (data.error) {
    throw new Error(data.error)
  }
  if (!data.plan) {
    throw new Error('No text generated by AI. Please try again.')
  }
  return data.plan
}




export const MOCK_PLAN = `## Day 1 - Upper Body Strength Focus
**Warm-up:** 5 mins arm circles, jumping jacks, shoulder mobility
**Main Workout:**
- Push-ups: 3 sets x 12 reps
- Dumbbell Rows: 3 sets x 10 reps
- Overhead Press: 3 sets x 10 reps
- Bicep Curls / Dips Superset: 3 sets x 12 reps
**Cool-down:** 5 mins chest & tricep static stretching

**Meals:**
- Breakfast: Oatmeal with berries, chia seeds & protein (350 kcal)
- Lunch: Grilled chicken salad with quinoa & avocado (450 kcal)
- Dinner: Baked salmon with sweet potato & broccoli (500 kcal)
- Snacks: Greek yogurt & almonds (300 kcal)
`

export function validateGeneratedPlan(planText: string): { isValid: boolean; dayCount: number; hasWorkouts: boolean; hasNutrition: boolean } {
  if (!planText || typeof planText !== 'string' || planText.trim().length < 50) {
    return { isValid: false, dayCount: 0, hasWorkouts: false, hasNutrition: false }
  }

  const dayMatches = planText.match(/##\s*Day\s*\d+/gi) || planText.match(/\bDay\s*\d+\b/gi) || []
  const hasWorkouts = /\b(workout|exercise|warm-up|warmup|circuit|sets|reps)\b/i.test(planText)
  const hasNutrition = /\b(breakfast|lunch|dinner|meals?|calorie|calories|kcal)\b/i.test(planText)

  const isValid = dayMatches.length >= 1 && hasWorkouts && hasNutrition
  return {
    isValid,
    dayCount: dayMatches.length,
    hasWorkouts,
    hasNutrition,
  }
}



